### ISSUE TITLE
Impossível fazer login no ArchLinux e ArcoLinux DDE Deepin V20 com STARDDE 5.0.6.7.

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/startdde#82]
Hello Deepin Linux Team

It is impossible to login to ArchLinux and ArcoLinux DDE Deepin Rolling with STARDDE 5.0.6.7. If someone has a problem with the login screen, just downgrade startdde 63 until they correct this infamous problem.

https://youtu.be/zM7ZRaSqBUE

More information:

https://bbs.deepin.org/post/204752
https://forum.archlinux-br.org/viewtopic.php?id=10689

Your considerations

Serial02

**Comment by taimoortalpur** [comment]
+1, learned the hard way.

**Comment by serial02** [comment]
Hi

The version released today from startdde 5.6.0.8 also does not work on ArchLinux and ArcoLinux DDE Deepin V20 Rolling.
This package needs to be fixed urgently

**Comment by vincenzocaselli** [comment]
+1, same problem here

**Comment by felixonmars** [comment]
This looks like a crash. Please check relevant logs in `/var/log/lightdm/seat0-greeter.log` and journal.

I cannot reproduce the issue here.

**Comment by vincenzocaselli** [comment]
Here is the content of my /var/log/lightdm/seat0-greeter.log:

```
2020-11-02, 13:21:52.192 [Debug  ] [                                                         0] restore numlock status to  false
2020-11-02, 13:21:52.196 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 13:21:52.198 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 13:21:52.208 [Debug  ] [                                                         0] check using swap partition!
2020-11-02, 13:21:52.208 [Debug  ] [                                                         0] "image_size: 6566354944, swap partition size: 0"
2020-11-02, 13:21:52.208 [Debug  ] [                                                         0] check using swap partition!
2020-11-02, 13:21:52.208 [Debug  ] [                                                         0] "image_size: 6566354944, swap partition size: 8627679232"
2020-11-02, 13:21:52.209 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-02, 13:21:52.209 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 13:21:52.254 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.256 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.263 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.273 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "gnome-classic" "gnome"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "gnome-xorg" "gnome"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "pantheon" "unknown"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "plasma" "plasma"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "i3" "unknown"
2020-11-02, 13:21:52.274 [Debug  ] [                                                         0] found session:  "i3-with-shmlog" "unknown"
2020-11-02, 13:21:52.293 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.295 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.299 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "gnome-classic" "gnome"
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "gnome-xorg" "gnome"
2020-11-02, 13:21:52.303 [Debug  ] [                                                         0] found session:  "pantheon" "unknown"
2020-11-02, 13:21:52.304 [Debug  ] [                                                         0] found session:  "plasma" "plasma"
2020-11-02, 13:21:52.304 [Debug  ] [                                                         0] found session:  "i3" "unknown"
2020-11-02, 13:21:52.304 [Debug  ] [                                                         0] found session:  "i3-with-shmlog" "unknown"
2020-11-02, 13:21:52.308 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.309 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.312 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "gnome-classic" "gnome"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "gnome-xorg" "gnome"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "pantheon" "unknown"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "plasma" "plasma"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "i3" "unknown"
2020-11-02, 13:21:52.317 [Debug  ] [                                                         0] found session:  "i3-with-shmlog" "unknown"
2020-11-02, 13:21:52.323 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.324 [Debug  ] [                                                         0] switch to user "vincenzo"
2020-11-02, 13:21:52.324 [Debug  ] [                                                         0] chosen session:  "deepin"
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] chosen session:  "deepin"
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] chosen session:  "deepin"
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.325 [Debug  ] [                                                         0] "vincenzo" default session is:  "deepin" 0
2020-11-02, 13:21:52.326 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.326 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.326 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.507 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.507 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.510 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] switch to user "vincenzo"
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] "vincenzo" default session is:  "deepin" 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.511 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.696 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] switch to user "vincenzo"
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] "vincenzo" default session is:  "deepin" 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0
2020-11-02, 13:21:52.697 [Debug  ] [                                                         0] 0

** (process:12938): CRITICAL **: 13:21:52.885: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed

** (process:12938): CRITICAL **: 13:21:52.885: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 500, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-02, 13:21:52.946 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-02, 13:21:52.946 [Debug  ] [                                                         0] itemIndex itemText: 0 "Italian"
2020-11-02, 13:21:52.946 [Debug  ] [                                                         0] XsetButtonsChecked: "Italian"
2020-11-02, 13:21:52.974 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "it")
2020-11-02, 13:21:52.978 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:52.978 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:52.978 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:52.978 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.978 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:52.990 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-02, 13:21:52.990 [Debug  ] [                                                         0] itemIndex itemText: 0 "Italian"
2020-11-02, 13:21:52.990 [Debug  ] [                                                         0] XsetButtonsChecked: "Italian"
2020-11-02, 13:21:53.014 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "it")
2020-11-02, 13:21:53.015 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.015 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.015 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.015 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 13:21:53.029 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-02, 13:21:53.029 [Debug  ] [                                                         0] itemIndex itemText: 0 "Italian"
2020-11-02, 13:21:53.029 [Debug  ] [                                                         0] XsetButtonsChecked: "Italian"
2020-11-02, 13:21:53.053 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "it")
2020-11-02, 13:21:53.053 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.053 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.053 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.053 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:53.065 [Debug  ] [                                                         0] pam prompt:  "Password: " 1
2020-11-02, 13:21:58.261 [Warning] [                                                         0] QFSFileEngine::open: No file name specified
No appenders assotiated with category qt.svg
[Warning] <> Cannot open file '', because: No file name specified
2020-11-02, 13:21:58.373 [Debug  ] [                                                         0] chosen session:  "plasma"
2020-11-02, 13:21:58.374 [Debug  ] [                                                         0] chosen session:  "plasma"
2020-11-02, 13:21:58.375 [Debug  ] [                                                         0] chosen session:  "plasma"
2020-11-02, 13:21:58.375 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:21:58.379 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 13:22:03.870 [Debug  ] [                                                         0] greeter authenticate user:  "vincenzo"  current user:  "vincenzo"
2020-11-02, 13:22:03.890 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-02, 13:22:03.897 [Debug  ] [                                                         0] start session =  "plasma"
addr2line: 'dde-lock': No such file
addr2line: 'dde-lock': No such file

```

**Comment by felixonmars** [comment]
It seems you are logging into plasma and thus no error is present. Please try seat0-greeter.log.old and see if it contains the unsuccessful DDE session.

**Comment by Cardellino** [comment]
Hello,

I had the same problem yesterday after performing arch linux update. Enter user and password -> screen briefly blacks out, then enter password again. I was able to fix the problem by downgrading (old version) .....

**Comment by vincenzocaselli** [comment]
@felixonmars you're right. Here it is the content of file **seat0-greeter.log.old** 

```
2020-11-02, 23:11:06.087 [Debug  ] [                                                         0] restore numlock status to  false
2020-11-02, 23:11:06.090 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 23:11:06.093 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] check using swap partition!
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] "image_size: 6566354944, swap partition size: 0"
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] check using swap partition!
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] "image_size: 6566354944, swap partition size: 8627679232"
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-02, 23:11:06.105 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-02, 23:11:06.300 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 23:11:06.303 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 23:11:06.323 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "gnome" "gnome"
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "gnome-classic" "gnome"
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "gnome-xorg" "gnome"
2020-11-02, 23:11:06.332 [Debug  ] [                                                         0] found session:  "pantheon" "unknown"
2020-11-02, 23:11:06.333 [Debug  ] [                                                         0] found session:  "plasma" "plasma"
2020-11-02, 23:11:06.333 [Debug  ] [                                                         0] found session:  "i3" "unknown"
2020-11-02, 23:11:06.333 [Debug  ] [                                                         0] found session:  "i3-with-shmlog" "unknown"
2020-11-02, 23:11:06.359 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 23:11:06.361 [Debug  ] [                                                         0] switch to user "vincenzo"
2020-11-02, 23:11:06.361 [Debug  ] [                                                         0] chosen session:  "deepin"
2020-11-02, 23:11:06.362 [Debug  ] [                                                         0] 0
2020-11-02, 23:11:06.362 [Debug  ] [                                                         0] "vincenzo" default session is:  "deepin" 0
2020-11-02, 23:11:06.363 [Debug  ] [                                                         0] 0
2020-11-02, 23:11:06.629 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-02, 23:11:06.629 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:5254): CRITICAL **: 23:11:06.629: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed

** (process:5254): CRITICAL **: 23:11:06.629: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
2020-11-02, 23:11:06.629 [Warning] [                                                         0] com.deepin.daemon.Accounts is not start, rechecking!
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 491, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-02, 23:11:06.678 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-02, 23:11:06.678 [Debug  ] [                                                         0] itemIndex itemText: 0 "Italian"
2020-11-02, 23:11:06.678 [Debug  ] [                                                         0] XsetButtonsChecked: "Italian"
2020-11-02, 23:11:06.700 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "it")
2020-11-02, 23:11:06.706 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 23:11:06.706 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 23:11:06.706 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-02, 23:11:06.720 [Debug  ] [                                                         0] pam prompt:  "Password: " 1
2020-11-02, 23:11:06.931 [Warning] [                                                         0] com.deepin.daemon.Accounts is not start, rechecking!
2020-11-02, 23:11:15.397 [Debug  ] [                                                         0] greeter authenticate user:  "vincenzo"  current user:  "vincenzo"
2020-11-02, 23:11:15.434 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-02, 23:11:15.449 [Debug  ] [                                                         0] start session =  "deepin"
addr2line: 'dde-lock': No such file
addr2line: 'dde-lock': No such file

```

**Comment by luebking** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1935383#p1935383

**Comment by Cardellino** [comment]
The error also occurs with version 5.6.0.7 to 9.
Password -> black screen -> always the same ....
[seat0-greeter.log.old.txt](https://github.com/linuxdeepin/startdde/files/5479922/seat0-greeter.log.old.txt)

**Comment by jeimison3** [comment]
Same here. Using UbuntuDDE.

`2020-11-03, 06:48:13.849 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 06:48:13.851 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 06:48:13.867 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 06:48:13.867 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 06:48:14.054 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:14.060 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:14.101 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 06:48:14.445 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:14.448 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 06:48:14.448 [Debug  ] [                                                         0] 0
2020-11-03, 06:48:14.448 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 06:48:14.453 [Debug  ] [                                                         0] 0
2020-11-03, 06:48:14.943 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:14.943 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:5968): CRITICAL **: 06:48:14.943: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 06:48:14.993 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 06:48:14.993 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 06:48:14.993 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 06:48:15.037 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 06:48:15.056 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:15.056 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:15.056 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:16.127 [Warning] [                                                         0] The X11 connection broke (error 1). Did the X11 server die?
2020-11-03, 06:48:16.127 [Warning] [                                                         0] QProcess: Destroyed while process ("onboard") is still running.
2020-11-03, 06:48:16.129 [Warning] [                                                         0] The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Sucesso) on X server ":0"
      after 17 requests (17 known processed) with 0 events remaining.
 [Warning] [                                                         0] QObject::~QObject: Timers cannot be stopped from another thread
addr2line: 'dde-lock': Não é esse arquivo
2020-11-03, 06:48:18.225 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 06:48:18.226 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 06:48:18.242 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 06:48:18.242 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 06:48:18.329 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:18.334 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:18.368 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 06:48:18.675 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:18.678 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 06:48:18.678 [Debug  ] [                                                         0] 0
2020-11-03, 06:48:18.678 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 06:48:18.681 [Debug  ] [                                                         0] 0
2020-11-03, 06:48:19.116 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 06:48:19.116 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:6675): CRITICAL **: 06:48:19.116: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 06:48:19.166 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 06:48:19.166 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 06:48:19.166 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 06:48:19.209 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 06:48:19.230 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:19.230 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:19.230 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 06:48:23.587 [Debug  ] [                                                         0] greeter authenticate user:  "jmoreno"  current user:  "jmoreno"
2020-11-03, 06:48:23.611 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-03, 06:48:23.646 [Debug  ] [                                                         0] start session =  "deepin"
addr2line: 'dde-lock': Não é esse arquivo
addr2line: 'dde-lock': Não é esse arquivo
2020-11-03, 09:51:07.867 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 09:51:07.869 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:51:07.884 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 09:51:07.884 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:51:08.080 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:08.086 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:08.128 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 09:51:08.464 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:08.467 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 09:51:08.467 [Debug  ] [                                                         0] 0
2020-11-03, 09:51:08.467 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 09:51:08.470 [Debug  ] [                                                         0] 0
2020-11-03, 09:51:08.965 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:08.965 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:4728): CRITICAL **: 09:51:08.965: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 09:51:09.012 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 09:51:09.012 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 09:51:09.012 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 09:51:09.058 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 09:51:09.078 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:09.078 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:09.078 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:10.951 [Warning] [                                                         0] The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Sucesso) on X server ":0"
      after 17 requests (17 known processed) with 0 events remaining.
2020-11-03, 09:51:10.951 [Warning] [                                                         0] QProcess: Destroyed while process ("onboard") is still running.
2020-11-03, 09:51:10.959 [Warning] [                                                         0] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
2020-11-03, 09:51:10.959 [Warning] [                                                         0] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
2020-11-03, 09:51:10.960 [Warning] [                                                         0] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
 [Warning] [                                                         0] QObject::~QObject: Timers cannot be stopped from another thread
addr2line: 'dde-lock': Não é esse arquivo
/etc/deepin/greeters.d/lightdm-deepin-greeter, linha 6:  4728 Falha de segmentação  (imagem do núcleo gravada) /usr/bin/lightdm-deepin-greeter
2020-11-03, 09:51:13.568 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 09:51:13.568 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:51:13.583 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 09:51:13.583 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:51:13.674 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:13.676 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:13.707 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 09:51:14.008 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:14.011 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 09:51:14.012 [Debug  ] [                                                         0] 0
2020-11-03, 09:51:14.012 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 09:51:14.015 [Debug  ] [                                                         0] 0
2020-11-03, 09:51:14.447 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:51:14.447 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:5481): CRITICAL **: 09:51:14.447: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 09:51:14.505 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 09:51:14.505 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 09:51:14.505 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 09:51:14.541 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 09:51:14.562 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:14.562 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:14.562 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:51:17.292 [Debug  ] [                                                         0] greeter authenticate user:  "jmoreno"  current user:  "jmoreno"
2020-11-03, 09:51:17.313 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-03, 09:51:17.346 [Debug  ] [                                                         0] start session =  "deepin"
addr2line: 'dde-lock': Não é esse arquivo
addr2line: 'dde-lock': Não é esse arquivo
2020-11-03, 09:55:28.054 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 09:55:28.056 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:55:28.071 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 09:55:28.071 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:55:28.259 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:28.265 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:28.303 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 09:55:28.620 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:28.623 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 09:55:28.623 [Debug  ] [                                                         0] 0
2020-11-03, 09:55:28.623 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 09:55:28.626 [Debug  ] [                                                         0] 0
2020-11-03, 09:55:29.083 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:29.083 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:6407): CRITICAL **: 09:55:29.083: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 09:55:29.138 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 09:55:29.138 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 09:55:29.138 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 09:55:29.175 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 09:55:29.196 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:29.196 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:29.196 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:31.092 [Warning] [                                                         0] The X11 connection broke (error 1). Did the X11 server die?
2020-11-03, 09:55:31.092 [Warning] [                                                         0] QProcess: Destroyed while process ("onboard") is still running.
2020-11-03, 09:55:31.093 [Warning] [                                                         0] The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Sucesso) on X server ":0"
      after 17 requests (17 known processed) with 0 events remaining.
 [Warning] [                                                         0] QObject::~QObject: Timers cannot be stopped from another thread
addr2line: 'dde-lock': Não é esse arquivo
2020-11-03, 09:55:33.075 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 09:55:33.076 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:55:33.090 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 09:55:33.090 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:55:33.181 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:33.183 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:33.219 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 09:55:33.519 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:33.522 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 09:55:33.522 [Debug  ] [                                                         0] 0
2020-11-03, 09:55:33.522 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 09:55:33.525 [Debug  ] [                                                         0] 0
2020-11-03, 09:55:33.943 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:55:33.943 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:7157): CRITICAL **: 09:55:33.943: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 09:55:33.996 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 09:55:33.996 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 09:55:33.996 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 09:55:34.033 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 09:55:34.045 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:34.045 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:34.045 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:55:36.708 [Debug  ] [                                                         0] greeter authenticate user:  "jmoreno"  current user:  "jmoreno"
2020-11-03, 09:55:36.730 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-03, 09:55:36.763 [Debug  ] [                                                         0] start session =  "deepin"
addr2line: 'dde-lock': Não é esse arquivo
addr2line: 'dde-lock': Não é esse arquivo
2020-11-03, 09:57:03.773 [Debug  ] [                                                         0] restore numlock status to  true
2020-11-03, 09:57:03.774 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:57:03.788 [Debug  ] [                                                         0] GreeterWorkek::onFirstTimeLogin -- FirstTime Login User Name is :  "The name com.deepin.daemon.Authenticate was not provided by any .service files"
2020-11-03, 09:57:03.788 [Debug  ] [                                                         0] Wrong, you shouldn't be here!
2020-11-03, 09:57:03.882 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:57:03.885 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:57:03.916 [Debug  ] [                                                         0] found session:  "deepin" "deepin"
2020-11-03, 09:57:04.234 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:57:04.236 [Debug  ] [                                                         0] switch to user "jmoreno"
2020-11-03, 09:57:04.236 [Debug  ] [                                                         0] 0
2020-11-03, 09:57:04.236 [Debug  ] [                                                         0] "jmoreno" default session is:  "deepin" 0
2020-11-03, 09:57:04.239 [Debug  ] [                                                         0] 0
2020-11-03, 09:57:04.674 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116
2020-11-03, 09:57:04.674 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 116

** (process:12036): CRITICAL **: 09:57:04.674: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 481, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-11-03, 09:57:04.716 [Debug  ] [                                                         0] m_layoutbuttons.length: 1 0
2020-11-03, 09:57:04.716 [Debug  ] [                                                         0] itemIndex itemText: 0 "Português (Brasil)"
2020-11-03, 09:57:04.716 [Debug  ] [                                                         0] XsetButtonsChecked: "Português (Brasil)"
2020-11-03, 09:57:04.769 [Debug  ] [                                                         0] 0 "" "setxkbmap" ("-model", "pc105", "-layout", "br")
2020-11-03, 09:57:04.789 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:57:04.789 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:57:04.789 [Info   ] [                                                         0] m_kbLayoutBorder->arrowHeight()--> 44
2020-11-03, 09:57:08.477 [Debug  ] [                                                         0] greeter authenticate user:  "jmoreno"  current user:  "jmoreno"
2020-11-03, 09:57:08.498 [Debug  ] [                                                         0] authentication complete, authenticated  true
2020-11-03, 09:57:08.532 [Debug  ] [                                                         0] start session =  "deepin"
`

**Comment by vincenzocaselli** [comment]
Hi,
tested now with 5.6.0.10-1 -> same behavior

**Comment by justforlxz** [comment]
thank you for your feedback. can you upload ~/.xsession-errors? maybe will see some errors. @serial02 @vincenzocaselli

**Comment by sayoojsamuel** [comment]
Here is the output of `~/.xsession-errors` while testing with `startdde 5.6.0.7-1`.   
I'm running Arch linux with the latest kernel `5.9.2-arch1-1`.
```
No xresources data found!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55d9ef094985]

goroutine 1 [running]:
main.launchCoreComponents(0xc0001de090)
	_/build/startdde/src/startdde-5.6.0.7/main.go:133 +0x2e5
main.main()
	_/build/startdde/src/startdde-5.6.0.7/main.go:225 +0x6ad
```

**Comment by GStore** [comment]
I can login but don't see the dock after installing deepin-kwin based on this forum post [https://bbs.archlinux.org/viewtopic.php?id=249305](https://bbs.archlinux.org/viewtopic.php?id=249305).

**Comment by justforlxz** [comment]
My machine has the same problem, and I am troubleshooting it.

**Comment by felixonmars** [comment]
Please try again with
deepin-desktop-schemas 5.8.0.20-3
startdde 5.6.0.10-2

They broke deepin-wm support yet again.

**Comment by Cardellino** [comment]
Hello felixonmars,

with the registration it works now but dde-dock is gone .. :(
After a second reboot, dde-dock will be gone again
->
dde-dock
Attribute Qt :: AA_EnableHighDpiScaling must be set before QCoreApplication is created.
2020-11-08, 13: 19: 33.593 [Info] [dguiapplicationhelper.cpp Dtk :: Gui :: DGuiApplicationHelper :: setSingleInstance 920] Process is started: pid = 1262 arguments = ("/ usr / bin / dde-dock" )
2020-11-08, 13: 19: 33.593 [Debug] [0] set single instance failed!
->

Only after a few minutes does the bar appear .....
Maybe someone should test too ...
[Log File.txt](https://github.com/linuxdeepin/startdde/files/5506312/Log.File.txt)

**Comment by Cardellino** [comment]
![Screen Capture_select-area_20201108142749](https://user-images.githubusercontent.com/73848158/98466273-c068b800-21ce-11eb-98db-18032ca41e02.png)

**Comment by sayoojsamuel** [comment]
@justforlxz is the missing dock resolved with your commit 1247ab7?

**Comment by serial02** [comment]
Hi

The same problem is occurring again, only now the login is initially all black and, when entering the password, the screen returns to TTY and then returns to the login screen. Only after that it allows you to enter the password and log in correctly. It's complicated (!)

![WhatsApp Image 2020-11-16 at 12 00 54](https://user-images.githubusercontent.com/32621790/99268705-49ea3c80-2804-11eb-82eb-8c09d99a6c76.jpeg)

**Comment by Cardellino** [comment]
Can only confirm that. I have to register 2 times then it's okay.
Slowly it won't be fun anymore ......

**Comment by serial02** [comment]
There was a new update from start-dde this morning, but the same problem remains.

`sudo pacman -Syyuu
[sudo] senha para edson: 
:: Sincronizando a base de dados de pacotes...
 core                                      129,5 KiB   863 KiB/s 00:00 [#######################################] 100%
 extra                                    1636,8 KiB   326 KiB/s 00:05 [#######################################] 100%
 community                                   5,2 MiB   335 KiB/s 00:16 [#######################################] 100%
 multilib-testing                         1323,0   B  0,00   B/s 00:00 [#######################################] 100%
 multilib                                  153,8 KiB   416 KiB/s 00:00 [#######################################] 100%
:: Iniciando atualização completa do sistema...
atenção: linux: ignorando atualização do pacote (5.9.arch1-1 => 5.9.8.arch1-1)
resolvendo dependências...
procurando pacotes conflitantes...
atenção: dependência cíclica detectada:
atenção: deepin-file-manager será instalado antes de sua dependência startdde
atenção: dependência cíclica detectada:
atenção: deepin-session-ui será instalado antes de sua dependência deepin-control-center

Pacotes (17) adobe-source-code-pro-fonts-2.032ro+1.052it+1.012var-1  deepin-control-center-5.3.0.41-1
             deepin-file-manager-1:5.2.0.63-1  deepin-movie-1:5.7.6.99-1  deepin-music-6.0.1.64-1
             deepin-qt5integration-5.1.0.9-1  deepin-screen-recorder-5.8.0.32-1  deepin-session-ui-5.3.0.22-1
             firefox-83.0-1  firefox-i18n-pt-br-83.0-1  geoip-database-20201110-1  geoip-database-extra-20201110-1
             libmm-glib-1.14.8-1  modemmanager-1.14.8-1  nodejs-15.2.1-1  startdde-5.6.0.12-1
             youtube-dl-2020.11.17-1

Tamanho total download:   119,97 MiB
Tamanho total instalado:  393,79 MiB
Alteração no tamanho:    -3,45 MiB

:: Continuar a instalação? [S/n] s
:: Obtendo pacotes...
 adobe-source-code-pro-fonts-2.032ro+...   944,2 KiB   258 KiB/s 00:04 [#######################################] 100%
 geoip-database-20201110-1-any            1543,4 KiB   336 KiB/s 00:05 [#######################################] 100%
 geoip-database-extra-20201110-1-any        20,3 MiB   314 KiB/s 01:06 [#######################################] 100%
 libmm-glib-1.14.8-1-x86_64                438,3 KiB   615 KiB/s 00:01 [#######################################] 100%
 firefox-83.0-1-x86_64                      58,5 MiB   557 KiB/s 01:48 [#######################################] 100%
 firefox-i18n-pt-br-83.0-1-any             453,7 KiB   476 KiB/s 00:01 [#######################################] 100%
 modemmanager-1.14.8-1-x86_64             1215,0 KiB   394 KiB/s 00:03 [#######################################] 100%
 deepin-qt5integration-5.1.0.9-1-x86_64    242,7 KiB   825 KiB/s 00:00 [#######################################] 100%
 deepin-file-manager-1:5.2.0.63-1-x86_64     4,1 MiB   533 KiB/s 00:08 [#######################################] 100%
 deepin-session-ui-5.3.0.22-1-x86_64       752,2 KiB   576 KiB/s 00:01 [#######################################] 100%
 startdde-5.6.0.12-1-x86_64                  3,4 MiB   469 KiB/s 00:07 [#######################################] 100%
 deepin-control-center-5.3.0.41-1-x86_64    10,9 MiB   550 KiB/s 00:20 [#######################################] 100%
 deepin-movie-1:5.7.6.99-1-x86_64         1112,7 KiB   577 KiB/s 00:02 [#######################################] 100%
 deepin-music-6.0.1.64-1-x86_64           1138,8 KiB   616 KiB/s 00:02 [#######################################] 100%
 deepin-screen-recorder-5.8.0.32-1-x86_64    4,3 MiB   467 KiB/s 00:10 [#######################################] 100%
 nodejs-15.2.1-1-x86_64                      8,4 MiB   506 KiB/s 00:17 [#######################################] 100%
 youtube-dl-2020.11.17-1-any                 2,2 MiB   536 KiB/s 00:04 [#######################################] 100%
(17/17) verificando chaves no chaveiro                                 [#######################################] 100%
(17/17) verificando integridade do pacote                              [#######################################] 100%
(17/17) carregando arquivos do pacote                                  [#######################################] 100%
(17/17) verificando conflitos de arquivos                              [#######################################] 100%
:: Processando alterações do pacote...
( 1/17) atualizando adobe-source-code-pro-fonts                        [#######################################] 100%
( 2/17) atualizando geoip-database                                     [#######################################] 100%
( 3/17) atualizando geoip-database-extra                               [#######################################] 100%
( 4/17) atualizando deepin-qt5integration                              [#######################################] 100%
( 5/17) atualizando deepin-file-manager                                [#######################################] 100%
( 6/17) atualizando deepin-session-ui                                  [#######################################] 100%
( 7/17) atualizando startdde                                           [#######################################] 100%
( 8/17) atualizando libmm-glib                                         [#######################################] 100%
( 9/17) atualizando deepin-control-center                              [#######################################] 100%
(10/17) atualizando deepin-movie                                       [#######################################] 100%
(11/17) atualizando deepin-music                                       [#######################################] 100%
(12/17) atualizando deepin-screen-recorder                             [#######################################] 100%
(13/17) atualizando firefox                                            [#######################################] 100%
(14/17) atualizando firefox-i18n-pt-br                                 [#######################################] 100%
(15/17) atualizando modemmanager                                       [#######################################] 100%
(16/17) atualizando nodejs                                             [#######################################] 100%
(17/17) atualizando youtube-dl                                         [#######################################] 100%
:: Executando hooks pós-transação...
(1/9) Reloading system manager configuration...
(2/9) Reloading device manager configuration...
(3/9) Arming ConditionNeedsUpdate...
(4/9) Reloading system bus configuration...
(5/9) Updating fontconfig cache...
(6/9) Compiling GSettings XML schema files...
(7/9) Updating icon theme caches...
(8/9) Updating the desktop file MIME type cache...
(9/9) Updating X fontdir indices...`

**Comment by Cardellino** [comment]
![Foto 1](https://user-images.githubusercontent.com/73848158/99408937-15a07a00-28f1-11eb-9791-532c212b50ae.jpg)
![Foto 2](https://user-images.githubusercontent.com/73848158/99408943-176a3d80-28f1-11eb-9b05-89a9c8befd74.jpg)
![Foto 3](https://user-images.githubusercontent.com/73848158/99408947-1802d400-28f1-11eb-95fe-70fecc305d96.jpg)
![Foto 4](https://user-images.githubusercontent.com/73848158/99408949-19340100-28f1-11eb-8cf0-5de6fa868512.jpg)

After the update from this morning and a new start
Photo 1 to 4
The bar can only be seen after 30 seconds

**Comment by Cardellino** [comment]
Hello,
before today's update the error with the double registration had disappeared.
Now the error is back. See pictures above

**Comment by serial02** [comment]
Hello @Cardellino 

Who knows, this report may help to find a solution to these problems.

Here is an update of the day and time:
https://pastebin.com/ZVVgbKYv
https://pastebin.com/raw/ZVVgbKYv

Below is a report of inconsistencies found in this Archlinux Rolling distribution after daily update.
https://pastebin.com/5Mzv0C1P
https://pastebin.com/raw/5Mzv0C1P

They say there is an update that fixes the dde-dock, but so far it has not been released.
https://github.com/linuxdeepin/dde-dock/issues/327

![imagem_2020-11-24_175123](https://user-images.githubusercontent.com/32621790/100149951-aa6d1f80-2e7d-11eb-81f5-c80f71c96fa2.png)

**Comment by Cardellino** [comment]
Hello,
I thank you.....

**Comment by serial02** [comment]
Hello

With the new update from dde-start the problem has returned. We couldn't get past the login screen and we have to downgrade the app to get on with life.
This is becoming a shame without size

@felixonmars 
@juteman

**Comment by Cardellino** [comment]
Downgrade 5.6.0.15-1 to 5.6.0.14-1 login screen okay.....
System Arch Linux

**Comment by mynameisjeffe** [comment]
Same problem here. I'm using Deepin Manjaro. Needed to downgrade to 5.6.0.14-1.

**Comment by serial02** [comment]
Hello

Dry logs to help them see if they can find a solution to this problem that has been going on for a long time.

[ArchLinux Rolling DDE-DOCK LOG.txt](https://github.com/linuxdeepin/startdde/files/5630488/ArchLinux.Rolling.DDE-DOCK.LOG.txt)

[ArchLinux Rolling LOG .txt](https://github.com/linuxdeepin/startdde/files/5630490/ArchLinux.Rolling.LOG.txt)

**Comment by yech1990** [comment]
can not switch to lock screen through start menu or keyboard shortcut. 

Need to run `dm-tool switch-to-greeter` from terminal manually.

**Comment by hillwoodroc** [comment]
Comfirm the same problem on openSUSE Leap.
